[tool.uv]
package = true
[project]
name = "everyone-knows-it"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.68.0",
    "dotenv>=0.9.9",
    "jinja2>=3.1.6",
    "typer>=0.17.4",
]
